server:
  port: 8002

baseUrl: http://localhost:9595/bank/accounts/getAccountDetailsByNumber/8119008115

spring:
  application:
    name: device-connectivity-v2

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

